<article class="section-builder rounded-2xl border border-slate-200 bg-slate-50 p-5 space-y-4" data-section>
  <div class="flex items-center justify-between gap-3"><div><span class="section-number text-[10px] font-bold uppercase tracking-wider text-blue-600">Section</span><h3 class="text-sm font-extrabold text-[#0a192f]">Content block</h3></div><div class="flex gap-2"><button type="button" data-move-up class="rounded-lg border bg-white px-3 py-1.5 text-xs">↑</button><button type="button" data-move-down class="rounded-lg border bg-white px-3 py-1.5 text-xs">↓</button><button type="button" data-remove-section class="rounded-lg border border-red-200 bg-white px-3 py-1.5 text-xs text-red-600">Remove</button></div></div>
  <div class="grid gap-4 sm:grid-cols-3"><div><label class="field">Section type *</label><select name="sections[{{ $sectionIndex }}][section_type]" required>@foreach($sectionTypes as $type)<option value="{{ $type }}" @selected(($section['section_type'] ?? '') === $type)>{{ ucwords(str_replace('_', ' ', $type)) }}</option>@endforeach</select></div><div><label class="field">Theme</label><select name="sections[{{ $sectionIndex }}][theme]"><option value="light" @selected(($section['theme'] ?? 'light') === 'light')>White</option><option value="soft" @selected(($section['theme'] ?? '') === 'soft')>Soft grey</option><option value="dark" @selected(($section['theme'] ?? '') === 'dark')>Dark navy</option></select></div><label class="mt-7 flex items-center gap-2 text-xs"><input type="checkbox" name="sections[{{ $sectionIndex }}][is_enabled]" value="1" @checked($section['is_enabled'] ?? true)> Show this section</label></div>
  <div class="grid gap-4 sm:grid-cols-2"><div><label class="field">Eyebrow / small label</label><input name="sections[{{ $sectionIndex }}][eyebrow]" value="{{ $section['eyebrow'] ?? '' }}"></div><div><label class="field">Heading</label><input name="sections[{{ $sectionIndex }}][heading]" value="{{ $section['heading'] ?? '' }}"></div></div>
  <div><label class="field">Body text</label><textarea name="sections[{{ $sectionIndex }}][body]" rows="3">{{ $section['body'] ?? '' }}</textarea></div>
  <div class="grid gap-4 sm:grid-cols-2"><div><label class="field">Section image</label><input type="file" name="sections[{{ $sectionIndex }}][image]" accept="image/jpeg,image/png,image/webp"><input type="hidden" name="sections[{{ $sectionIndex }}][existing_image_path]" value="{{ $section['existing_image_path'] ?? '' }}">@if($section['existing_image_path'] ?? null)<p class="help">Current: {{ basename($section['existing_image_path']) }}</p>@endif</div><div><label class="field">Image alt text</label><input name="sections[{{ $sectionIndex }}][image_alt]" value="{{ $section['image_alt'] ?? '' }}"><p class="help">Required whenever an image is present.</p></div></div>
  <div class="grid gap-4 sm:grid-cols-2"><div><label class="field">CTA label</label><input name="sections[{{ $sectionIndex }}][cta_label]" value="{{ $section['cta_label'] ?? '' }}"></div><div><label class="field">CTA URL</label><input name="sections[{{ $sectionIndex }}][cta_url]" value="{{ $section['cta_url'] ?? '' }}" placeholder="/instant-quote"></div></div>
  <div class="rounded-xl border border-slate-200 bg-white p-4"><div class="mb-4 flex items-center justify-between"><div><h4 class="text-xs font-extrabold text-[#0a192f]">Repeatable items</h4><p class="help">Features, steps, regions, FAQ rows or comparison rows.</p></div><button type="button" data-add-item class="rounded-lg bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700">+ Add item</button></div><div class="space-y-3" data-items>@foreach(($section['items'] ?? []) as $itemIndex => $item) @include('admin.content-pages._section-item', ['sectionIndex' => $sectionIndex, 'itemIndex' => $itemIndex, 'item' => $item]) @endforeach</div></div>
</article>
