@extends('admin.layout')
@section('content')
<style>
.content-form label.field{display:block;font-size:12px;font-weight:700;margin-bottom:7px;color:#0a192f}.content-form input:not([type=checkbox]):not([type=file]),.content-form textarea,.content-form select{width:100%;border:1px solid #e2e8f0;border-radius:10px;padding:10px 12px;font-size:13px;background:white}.content-form .help{font-size:11px;color:#64748b;line-height:1.6;margin-top:5px}.content-form .panel{background:white;border:1px solid #e2e8f0;border-radius:20px;padding:24px}
</style>
@php
$formSections = old('sections');
if ($formSections === null) {
    $formSections = $page->exists ? $page->sections->map(fn($section) => [
        'section_type' => $section->section_type, 'eyebrow' => $section->eyebrow,
        'heading' => $section->heading, 'body' => $section->body,
        'existing_image_path' => $section->image_path, 'image_alt' => $section->image_alt,
        'cta_label' => $section->cta_label, 'cta_url' => $section->cta_url,
        'theme' => $section->theme, 'is_enabled' => $section->is_enabled,
        'items' => $section->items->map(fn($item) => [
            'title' => $item->title, 'subtitle' => $item->subtitle, 'description' => $item->description,
            'badge' => $item->badge, 'value' => $item->value, 'icon' => $item->icon,
            'existing_image_path' => $item->image_path, 'image_alt' => $item->image_alt,
            'link_label' => $item->link_label, 'link_url' => $item->link_url,
        ])->all(),
    ])->all() : [];
}
$featureText = old('card_features_text', implode("\n", $page->card_features ?? []));
$detailText = old('card_details_text', collect($page->card_details ?? [])->map(fn($row) => ($row['label'] ?? '').'|'.($row['value'] ?? ''))->implode("\n"));
@endphp
<div class="flex flex-wrap items-center justify-between gap-4"><div><a href="{{ route('admin.content-pages.index') }}" class="text-xs font-bold text-blue-600">← Services & Coverage</a><h1 class="mt-3 text-3xl font-extrabold text-[#0a192f]">{{ $page->exists ? 'Edit '.$page->title : 'Create service' }}</h1><p class="mt-2 text-sm text-slate-500">Add only the sections you need. Empty blocks are never displayed on the website.</p></div>@if($page->exists && $page->status === 'published')<a href="{{ rtrim(config('app.frontend_url'), '/') }}/{{ $page->slug }}" target="_blank" rel="noopener" class="rounded-full border border-slate-200 bg-white px-5 py-3 text-xs font-bold">View on website ↗</a>@endif</div>
@if($errors->any())<div role="alert" class="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-800"><strong>Please check the following:</strong><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form id="content-page-form" class="content-form grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_340px]" method="POST" enctype="multipart/form-data" action="{{ $page->exists ? route('admin.content-pages.update', $page) : route('admin.content-pages.store') }}">
@csrf @if($page->exists) @method('PUT') @endif
<input type="hidden" name="page_type" value="{{ $page->page_type ?: 'service' }}">
<div class="min-w-0 space-y-6">
  <section class="panel space-y-5"><h2 class="text-lg font-extrabold">Page identity</h2><div><label class="field" for="title">Page title *</label><input id="title" name="title" required maxlength="255" value="{{ old('title', $page->title) }}"></div><div class="grid gap-5 sm:grid-cols-2"><div><label class="field" for="navigation_title">Navigation title</label><input id="navigation_title" name="navigation_title" value="{{ old('navigation_title', $page->navigation_title) }}"></div><div><label class="field" for="slug">URL slug *</label><input id="slug" name="slug" required value="{{ old('slug', $page->slug) }}" @readonly($page->page_type !== 'service')><p class="help">Website URL: /<span id="slug-preview">{{ old('slug', $page->slug) }}</span></p></div></div><div class="grid gap-5 sm:grid-cols-2"><div><label class="field" for="icon">Icon</label><select id="icon" name="icon">@foreach(['truck','zap','calendar','package','refresh','activity','file-text','map-pin','building','clock','shield'] as $icon)<option value="{{ $icon }}" @selected(old('icon', $page->icon) === $icon)>{{ ucwords(str_replace('-', ' ', $icon)) }}</option>@endforeach</select></div><div><label class="field" for="sort_order">Display order</label><input id="sort_order" name="sort_order" type="number" min="0" max="10000" value="{{ old('sort_order', $page->sort_order ?? 0) }}"></div></div><div><label class="field" for="summary">Short summary</label><textarea id="summary" name="summary" rows="3">{{ old('summary', $page->summary) }}</textarea></div></section>
  <section class="panel space-y-5"><h2 class="text-lg font-extrabold">Hero section</h2><div class="grid gap-5 sm:grid-cols-2"><div><label class="field">Badge</label><input name="hero_badge" value="{{ old('hero_badge', $page->hero_badge) }}"></div><div><label class="field">Hero heading</label><input name="hero_title" value="{{ old('hero_title', $page->hero_title) }}"></div></div><div><label class="field">Hero description</label><textarea name="hero_description" rows="4">{{ old('hero_description', $page->hero_description) }}</textarea></div><div class="grid gap-5 sm:grid-cols-2"><div><label class="field">Primary button label</label><input name="primary_cta_label" value="{{ old('primary_cta_label', $page->primary_cta_label) }}"></div><div><label class="field">Primary button URL</label><input name="primary_cta_url" value="{{ old('primary_cta_url', $page->primary_cta_url) }}"></div></div><div class="grid gap-5 sm:grid-cols-2"><div><label class="field">Hero image</label><input type="file" name="hero_image" accept="image/jpeg,image/png,image/webp"><input type="hidden" name="existing_hero_image_path" value="{{ $page->hero_image_path }}">@if($page->hero_image_path)<img src="{{ Storage::disk('public')->url($page->hero_image_path) }}" alt="" class="mt-3 h-24 rounded-xl object-cover">@endif</div><div><label class="field">Hero image alt text</label><input name="hero_image_alt" value="{{ old('hero_image_alt', $page->hero_image_alt) }}"><p class="help">Required if a hero image is used.</p></div></div></section>
  @if($page->page_type === 'service')<section class="panel space-y-5"><h2 class="text-lg font-extrabold">Service directory card</h2><div class="grid gap-5 sm:grid-cols-2"><div><label class="field">Badge</label><input name="card_badge" value="{{ old('card_badge', $page->card_badge) }}"></div><div><label class="field">Subtitle</label><input name="card_subtitle" value="{{ old('card_subtitle', $page->card_subtitle) }}"></div></div><div><label class="field">Card description</label><textarea name="card_description" rows="3">{{ old('card_description', $page->card_description) }}</textarea></div><div class="grid gap-5 sm:grid-cols-2"><div><label class="field">Feature bullets</label><textarea name="card_features_text" rows="6" placeholder="One feature per line">{{ $featureText }}</textarea></div><div><label class="field">Booking details</label><textarea name="card_details_text" rows="6" placeholder="Label|Value, one per line">{{ $detailText }}</textarea></div></div><div class="grid gap-5 sm:grid-cols-2"><div><label class="field">Card image</label><input type="file" name="card_image" accept="image/jpeg,image/png,image/webp"><input type="hidden" name="existing_card_image_path" value="{{ $page->card_image_path }}"></div><div><label class="field">Card image alt text</label><input name="card_image_alt" value="{{ old('card_image_alt', $page->card_image_alt) }}"></div></div></section>@endif
  <section class="panel space-y-5"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-lg font-extrabold">Repeatable page sections</h2><p class="help">Any section type can be added more than once and moved into any order.</p></div><button type="button" id="add-section" class="rounded-full bg-blue-50 px-5 py-2.5 text-xs font-bold text-blue-700">+ Add section</button></div><div id="sections" class="space-y-5">@foreach($formSections as $sectionIndex => $section) @include('admin.content-pages._section', compact('sectionIndex', 'section', 'sectionTypes')) @endforeach</div></section>
  <section class="panel space-y-5"><h2 class="text-lg font-extrabold">Search engine settings</h2><div><label class="field">Meta title</label><input name="meta_title" maxlength="255" value="{{ old('meta_title', $page->meta_title) }}"><p class="help">Aim for roughly 50–60 characters.</p></div><div><label class="field">Meta description</label><textarea name="meta_description" rows="3" maxlength="500">{{ old('meta_description', $page->meta_description) }}</textarea><p class="help">Aim for roughly 150–160 characters.</p></div><div><label class="field">Meta keywords</label><input name="meta_keywords" maxlength="1000" value="{{ old('meta_keywords', $page->meta_keywords) }}" placeholder="same day courier, UK delivery"></div><div class="grid gap-5 sm:grid-cols-2"><div><label class="field">Social title</label><input name="og_title" value="{{ old('og_title', $page->og_title) }}"></div><div><label class="field">Social description</label><textarea name="og_description" rows="2">{{ old('og_description', $page->og_description) }}</textarea></div></div><div><label class="field">Social sharing image</label><input type="file" name="og_image" accept="image/jpeg,image/png,image/webp"><input type="hidden" name="existing_og_image_path" value="{{ $page->og_image_path }}"></div><label class="flex items-center gap-2 text-xs"><input type="checkbox" name="noindex" value="1" @checked(old('noindex', $page->noindex))> Ask search engines not to index this page</label><label class="flex items-center gap-2 text-xs"><input type="checkbox" name="nofollow" value="1" @checked(old('nofollow', $page->nofollow))> Ask search engines not to follow links</label></section>
</div>
<aside class="space-y-6 xl:sticky xl:top-6"><section class="panel space-y-5"><h2 class="text-lg font-extrabold">Publishing</h2><div><label class="field">Visibility</label><select name="status"><option value="draft" @selected(old('status', $page->status) === 'draft')>Draft — admin only</option><option value="published" @selected(old('status', $page->status) === 'published')>Published — live website</option></select></div><button class="w-full rounded-full bg-[#c6ff00] px-6 py-3.5 text-sm font-extrabold text-[#0a192f]">Save page</button></section><section class="panel"><h2 class="text-sm font-extrabold">Section guide</h2><ul class="mt-3 space-y-2 text-xs leading-5 text-slate-600"><li><strong>Feature grid:</strong> benefits or service capabilities.</li><li><strong>Steps:</strong> numbered process.</li><li><strong>Region grid:</strong> title, badge/timing, description/hubs and value/postcodes.</li><li><strong>FAQ:</strong> item title is the question; description is the answer.</li><li><strong>Comparison:</strong> title is feature; subtitle and description are the two values.</li><li><strong>CTA:</strong> heading, body and button fields.</li></ul></section></aside>
</form>
<template id="section-template"><article class="section-builder rounded-2xl border border-slate-200 bg-slate-50 p-5 space-y-4" data-section><div class="flex items-center justify-between"><h3 class="text-sm font-extrabold">New section</h3><div class="flex gap-2"><button type="button" data-move-up class="rounded-lg border bg-white px-3 py-1.5 text-xs">↑</button><button type="button" data-move-down class="rounded-lg border bg-white px-3 py-1.5 text-xs">↓</button><button type="button" data-remove-section class="text-xs font-bold text-red-600">Remove</button></div></div><div class="grid gap-4 sm:grid-cols-3"><div><label class="field">Section type *</label><select name="sections[__SECTION__][section_type]">@foreach($sectionTypes as $type)<option value="{{ $type }}">{{ ucwords(str_replace('_', ' ', $type)) }}</option>@endforeach</select></div><div><label class="field">Theme</label><select name="sections[__SECTION__][theme]"><option value="light">White</option><option value="soft">Soft grey</option><option value="dark">Dark navy</option></select></div><label class="mt-7 flex items-center gap-2 text-xs"><input type="checkbox" name="sections[__SECTION__][is_enabled]" value="1" checked> Show section</label></div><div class="grid gap-4 sm:grid-cols-2"><div><label class="field">Eyebrow</label><input name="sections[__SECTION__][eyebrow]"></div><div><label class="field">Heading</label><input name="sections[__SECTION__][heading]"></div></div><div><label class="field">Body text</label><textarea name="sections[__SECTION__][body]" rows="3"></textarea></div><div class="grid gap-4 sm:grid-cols-2"><div><label class="field">Section image</label><input type="file" name="sections[__SECTION__][image]" accept="image/jpeg,image/png,image/webp"><input type="hidden" name="sections[__SECTION__][existing_image_path]"></div><div><label class="field">Image alt text</label><input name="sections[__SECTION__][image_alt]"></div></div><div class="grid gap-4 sm:grid-cols-2"><div><label class="field">CTA label</label><input name="sections[__SECTION__][cta_label]"></div><div><label class="field">CTA URL</label><input name="sections[__SECTION__][cta_url]"></div></div><div class="rounded-xl border bg-white p-4"><div class="mb-4 flex justify-between"><strong class="text-xs">Repeatable items</strong><button type="button" data-add-item class="text-xs font-bold text-blue-700">+ Add item</button></div><div class="space-y-3" data-items></div></div></article></template>
<template id="item-template"><div class="section-item rounded-xl border bg-slate-50 p-4 space-y-3" data-item><div class="flex justify-end"><button type="button" data-remove-item class="text-xs font-bold text-red-600">Remove item</button></div><div class="grid gap-3 sm:grid-cols-2"><div><label class="field">Title / question</label><input name="sections[__SECTION__][items][__ITEM__][title]"></div><div><label class="field">Subtitle</label><input name="sections[__SECTION__][items][__ITEM__][subtitle]"></div><div><label class="field">Badge / timing</label><input name="sections[__SECTION__][items][__ITEM__][badge]"></div><div><label class="field">Value / postcodes</label><input name="sections[__SECTION__][items][__ITEM__][value]"></div></div><div><label class="field">Description / answer</label><textarea name="sections[__SECTION__][items][__ITEM__][description]" rows="2"></textarea></div><div class="grid gap-3 sm:grid-cols-3"><div><label class="field">Icon key</label><input name="sections[__SECTION__][items][__ITEM__][icon]"></div><div><label class="field">Link label</label><input name="sections[__SECTION__][items][__ITEM__][link_label]"></div><div><label class="field">Link URL</label><input name="sections[__SECTION__][items][__ITEM__][link_url]"></div></div><div class="grid gap-3 sm:grid-cols-2"><div><label class="field">Item image</label><input type="file" name="sections[__SECTION__][items][__ITEM__][image]" accept="image/jpeg,image/png,image/webp"><input type="hidden" name="sections[__SECTION__][items][__ITEM__][existing_image_path]"></div><div><label class="field">Image alt text</label><input name="sections[__SECTION__][items][__ITEM__][image_alt]"></div></div></div></template>
<script src="/js/content-page-builder.js?v=1"></script>
@endsection
