@extends('admin.layout')
@section('content')
<style>.service-form label.field{display:block;font-size:12px;font-weight:700;margin-bottom:7px;color:#0a192f}.service-form input:not([type=checkbox]):not([type=file]),.service-form textarea,.service-form select{width:100%;border:1px solid #e2e8f0;border-radius:10px;padding:10px 12px;font-size:13px;background:white}.service-form .help{font-size:11px;color:#64748b;line-height:1.6;margin-top:5px}.service-form .panel{background:white;border:1px solid #e2e8f0;border-radius:20px;padding:24px}</style>
@php
$formSections = old('sections');
if ($formSections === null) $formSections = $service->exists ? $service->sections->map(fn($section) => [
  'section_type'=>$section->section_type,'anchor_id'=>$section->anchor_id,'label'=>$section->label,'heading'=>$section->heading,'intro'=>$section->intro,'body'=>$section->body,
  'callout_heading'=>$section->callout_heading,'callout_body'=>$section->callout_body,'existing_image_path'=>$section->image_path,'image_alt'=>$section->image_alt,
  'show_in_sidebar'=>$section->show_in_sidebar,'is_enabled'=>$section->is_enabled,
  'items'=>$section->items->map(fn($item)=>['badge'=>$item->badge,'title'=>$item->title,'body'=>$item->body,'link_label'=>$item->link_label,'link_url'=>$item->link_url,'existing_image_path'=>$item->image_path,'image_alt'=>$item->image_alt])->all(),
])->all() : [];
$featureText=old('card_features_text',implode("\n",$service->card_features??[]));
$detailText=old('card_details_text',collect($service->card_details??[])->map(fn($row)=>($row['label']??'').'|'.($row['value']??''))->implode("\n"));
$pointsText=old('hero_points_text',implode("\n",$service->hero_points??[]));
@endphp
<div class="flex flex-wrap items-center justify-between gap-4"><div><a href="{{ route('admin.services.index') }}" class="text-xs font-bold text-blue-600">← Services</a><h1 class="mt-3 text-3xl font-extrabold text-[#0a192f]">{{ $service->exists ? 'Edit '.$service->title : 'Create service' }}</h1><p class="mt-2 text-sm text-slate-500">Fields follow the live service-page template from hero through sticky sidebar and final CTA.</p></div>@if($service->exists&&$service->status==='published')<a href="{{ rtrim(config('app.frontend_url'), '/') }}/{{ $service->slug }}" target="_blank" rel="noopener" class="rounded-full border bg-white px-5 py-3 text-xs font-bold">View website ↗</a>@endif</div>
@if($errors->any())<div role="alert" class="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-800"><strong>Please check:</strong><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form id="service-form" class="service-form grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_340px]" method="POST" enctype="multipart/form-data" action="{{ $service->exists?route('admin.services.update',$service):route('admin.services.store') }}">@csrf @if($service->exists)@method('PUT')@endif
<div class="min-w-0 space-y-6">
<section class="panel space-y-5"><h2 class="text-lg font-extrabold">Service identity & directory card</h2><div class="grid gap-5 sm:grid-cols-2"><div><label class="field">Service title *</label><input id="title" name="title" required value="{{ old('title',$service->title) }}"></div><div><label class="field">Navigation title</label><input name="navigation_title" value="{{ old('navigation_title',$service->navigation_title) }}"></div><div><label class="field">URL slug *</label><input id="slug" name="slug" required value="{{ old('slug',$service->slug) }}"><p class="help">/<span id="slug-preview">{{ old('slug',$service->slug) }}</span></p></div><div><label class="field">Icon</label><select name="icon">@foreach(['truck','zap','calendar','package','refresh','activity','file-text','clock','shield'] as $icon)<option value="{{ $icon }}" @selected(old('icon',$service->icon)===$icon)>{{ ucwords(str_replace('-',' ',$icon)) }}</option>@endforeach</select></div></div><div><label class="field">Short summary</label><textarea name="summary" rows="3">{{ old('summary',$service->summary) }}</textarea></div><div class="grid gap-5 sm:grid-cols-2"><div><label class="field">Card badge</label><input name="card_badge" value="{{ old('card_badge',$service->card_badge) }}"></div><div><label class="field">Card subtitle</label><input name="card_subtitle" value="{{ old('card_subtitle',$service->card_subtitle) }}"></div></div><div><label class="field">Card description</label><textarea name="card_description" rows="3">{{ old('card_description',$service->card_description) }}</textarea></div><div class="grid gap-5 sm:grid-cols-2"><div><label class="field">Feature bullets</label><textarea name="card_features_text" rows="5" placeholder="One feature per line">{{ $featureText }}</textarea></div><div><label class="field">Booking details</label><textarea name="card_details_text" rows="5" placeholder="Label|Value">{{ $detailText }}</textarea></div></div></section>
<section class="panel space-y-5"><h2 class="text-lg font-extrabold">Template hero</h2><div><label class="field">Eyebrow</label><input name="hero_eyebrow" value="{{ old('hero_eyebrow',$service->hero_eyebrow) }}"></div><div><label class="field">Main heading</label><input name="hero_title" value="{{ old('hero_title',$service->hero_title) }}"></div><div><label class="field">Description</label><textarea name="hero_description" rows="5">{{ old('hero_description',$service->hero_description) }}</textarea></div><div class="grid gap-5 sm:grid-cols-2">@foreach([['hero_primary_label','Primary button label'],['hero_primary_url','Primary button URL'],['hero_secondary_label','Secondary button label'],['hero_secondary_url','Secondary button URL']] as [$name,$label])<div><label class="field">{{ $label }}</label><input name="{{ $name }}" value="{{ old($name,$service->$name) }}"></div>@endforeach</div><div><label class="field">Trust points</label><textarea name="hero_points_text" rows="4" placeholder="One point per line">{{ $pointsText }}</textarea></div><div class="grid gap-5 sm:grid-cols-2"><div><label class="field">Optional hero image</label><input type="file" name="hero_image" accept="image/jpeg,image/png,image/webp"><input type="hidden" name="existing_hero_image_path" value="{{ $service->hero_image_path }}"></div><div><label class="field">Hero image alt text</label><input name="hero_image_alt" value="{{ old('hero_image_alt',$service->hero_image_alt) }}"><p class="help">Required when an image is used.</p></div></div></section>
<section class="panel space-y-5"><h2 class="text-lg font-extrabold">Direct-route visual</h2><div class="grid gap-5 sm:grid-cols-2">@foreach([['route_kicker','Top label'],['route_counter','Counter'],['collection_label','Collection label'],['collection_detail','Collection detail'],['delivery_label','Delivery label'],['delivery_detail','Delivery detail'],['route_footer','Footer label'],['route_status','Status']] as [$name,$label])<div><label class="field">{{ $label }}</label><input name="{{ $name }}" value="{{ old($name,$service->$name) }}"></div>@endforeach</div><div><label class="field">Visual heading</label><textarea name="route_title" rows="3" placeholder="Use a new line for each line">{{ old('route_title',$service->route_title) }}</textarea></div></section>
<section class="panel space-y-5"><h2 class="text-lg font-extrabold">Notice strip</h2><div><label class="field">Bold title</label><input name="notice_title" value="{{ old('notice_title',$service->notice_title) }}"></div><div><label class="field">Notice text</label><textarea name="notice_body" rows="3">{{ old('notice_body',$service->notice_body) }}</textarea></div></section>
<section class="panel space-y-5"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-lg font-extrabold">Long-form service content</h2><p class="help">Add and reorder the same blocks used by the supplied design.</p></div><button type="button" id="add-section" class="rounded-full bg-blue-50 px-5 py-2.5 text-xs font-bold text-blue-700">+ Add block</button></div><div id="sections" class="space-y-5">@foreach($formSections as $sectionIndex=>$section)@include('admin.services._section',compact('sectionIndex','section','sectionTypes'))@endforeach</div></section>
<section class="panel space-y-5"><h2 class="text-lg font-extrabold">Sticky sidebar</h2><div><label class="field">Urgent card heading</label><input name="sidebar_title" value="{{ old('sidebar_title',$service->sidebar_title) }}"></div><div><label class="field">Urgent card text</label><textarea name="sidebar_body" rows="3">{{ old('sidebar_body',$service->sidebar_body) }}</textarea></div><div class="grid gap-5 sm:grid-cols-2"><div><label class="field">Button label</label><input name="sidebar_cta_label" value="{{ old('sidebar_cta_label',$service->sidebar_cta_label) }}"></div><div><label class="field">Button URL</label><input name="sidebar_cta_url" value="{{ old('sidebar_cta_url',$service->sidebar_cta_url) }}"></div></div><div><label class="field">Helpful details card</label><textarea name="sidebar_helpful_details" rows="4">{{ old('sidebar_helpful_details',$service->sidebar_helpful_details) }}</textarea></div></section>
<section class="panel space-y-5"><h2 class="text-lg font-extrabold">Bottom CTA</h2><div><label class="field">Heading</label><input name="bottom_cta_title" value="{{ old('bottom_cta_title',$service->bottom_cta_title) }}"></div><div><label class="field">Text</label><textarea name="bottom_cta_body" rows="3">{{ old('bottom_cta_body',$service->bottom_cta_body) }}</textarea></div><div class="grid gap-5 sm:grid-cols-2"><div><label class="field">Button label</label><input name="bottom_cta_label" value="{{ old('bottom_cta_label',$service->bottom_cta_label) }}"></div><div><label class="field">Button URL</label><input name="bottom_cta_url" value="{{ old('bottom_cta_url',$service->bottom_cta_url) }}"></div></div></section>
<section class="panel space-y-5"><h2 class="text-lg font-extrabold">SEO</h2>@foreach([['meta_title','Meta title'],['meta_keywords','Meta keywords'],['og_title','Social title']] as [$name,$label])<div><label class="field">{{ $label }}</label><input name="{{ $name }}" value="{{ old($name,$service->$name) }}"></div>@endforeach @foreach([['meta_description','Meta description'],['og_description','Social description']] as [$name,$label])<div><label class="field">{{ $label }}</label><textarea name="{{ $name }}" rows="3">{{ old($name,$service->$name) }}</textarea></div>@endforeach <div><label class="field">Social image</label><input type="file" name="og_image" accept="image/jpeg,image/png,image/webp"><input type="hidden" name="existing_og_image_path" value="{{ $service->og_image_path }}"></div><label class="flex gap-2 text-xs"><input type="checkbox" name="noindex" value="1" @checked(old('noindex',$service->noindex))> Noindex</label><label class="flex gap-2 text-xs"><input type="checkbox" name="nofollow" value="1" @checked(old('nofollow',$service->nofollow))> Nofollow</label></section>
</div>
<aside class="space-y-6 xl:sticky xl:top-6"><section class="panel space-y-5"><h2 class="text-lg font-extrabold">Publishing</h2><div><label class="field">Visibility</label><select name="status"><option value="draft" @selected(old('status',$service->status)==='draft')>Draft</option><option value="published" @selected(old('status',$service->status)==='published')>Published</option></select></div><div><label class="field">Display order</label><input type="number" min="0" max="10000" name="sort_order" value="{{ old('sort_order',$service->sort_order??0) }}"></div><button class="w-full rounded-full bg-[#c6ff00] px-6 py-3.5 text-sm font-extrabold text-[#0a192f]">Save service</button></section><section class="panel"><h2 class="text-sm font-extrabold">Block guide</h2><ul class="mt-3 space-y-2 text-xs leading-5 text-slate-600"><li><strong>Content:</strong> label, heading, intro, paragraphs and optional callout.</li><li><strong>Steps:</strong> badge, title and body for each item.</li><li><strong>Tiles:</strong> two-column information cards.</li><li><strong>FAQ:</strong> item title is question; body is answer.</li><li><strong>Related:</strong> linked service cards.</li></ul></section></aside>
</form>
<template id="section-template">@include('admin.services._section-template',['sectionTypes'=>$sectionTypes])</template>
<template id="item-template">@include('admin.services._item-template')</template>
<script src="/js/service-builder.js?v=1"></script>
@endsection
