@extends('admin.layout')
@section('content')
<link rel="stylesheet" href="/vendor/jodit/jodit.min.css">
<style>
.blog-form label.field {display:block;font-size:12px;font-weight:700;margin-bottom:8px;color:#0a192f}.blog-form input:not([type=checkbox]):not([type=file]),.blog-form textarea,.blog-form select{width:100%;border:1px solid #e2e8f0;border-radius:10px;padding:11px 13px;font-size:13px;background:white}.blog-form .help{font-size:11px;color:#64748b;line-height:1.7;margin-top:6px}.blog-form .panel{background:white;border:1px solid #e2e8f0;border-radius:20px;padding:24px}.blog-form .jodit-wysiwyg{font-size:16px;line-height:1.8;color:#475569}.blog-form .jodit-wysiwyg h1{font-size:36px;font-weight:800;color:#0a192f}.blog-form .jodit-wysiwyg h2{font-size:28px;font-weight:800;color:#0a192f}.blog-form .jodit-wysiwyg h3{font-size:22px;font-weight:700;color:#0a192f}.blog-form .jodit-wysiwyg ul{list-style:disc;padding-left:24px}.blog-form .jodit-wysiwyg ol{list-style:decimal;padding-left:24px}.blog-form .jodit-wysiwyg a{color:#0066ff;text-decoration:underline}.blog-form .jodit-wysiwyg p{margin-bottom:16px}.blog-form .jodit-wysiwyg img{max-width:100%}.blog-form .jodit-container{border-radius:12px!important;overflow:hidden}.blog-form .jodit-wysiwyg table td{padding:12px;border:1px solid #e2e8f0}
</style>
<div class="flex items-center justify-between"><div><a href="{{ route('admin.blogs.index') }}" class="text-xs font-bold text-blue-600">← All blogs</a><h1 class="mt-3 text-3xl font-extrabold text-[#0a192f]">{{ $blog->exists ? 'Edit blog' : 'Create a blog' }}</h1></div>@if($blog->exists && $blog->status === 'published')<a href="{{ rtrim(config('app.frontend_url'), '/') }}/blog/{{ $blog->slug }}" target="_blank" rel="noopener" class="rounded-full border border-slate-200 bg-white px-5 py-3 text-xs font-bold">View on website ↗</a>@endif</div>
@if($errors->any())<div role="alert" class="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-800"><strong>Please check the following:</strong><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form id="blog-form" class="blog-form grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_320px]" method="POST" enctype="multipart/form-data" action="{{ $blog->exists ? route('admin.blogs.update', $blog) : route('admin.blogs.store') }}">
@csrf @if($blog->exists) @method('PUT') @endif
<div class="min-w-0 space-y-6">
<section class="panel space-y-5"><h2 class="text-lg font-extrabold">Article details</h2><div><label for="title" class="field">Blog title *</label><input id="title" name="title" required maxlength="255" value="{{ old('title', $blog->title) }}"><p class="help">Used for blog cards and search. Add the visible article heading in the editor below.</p></div><div class="grid gap-5 sm:grid-cols-2"><div><label for="slug" class="field">URL slug *</label><input id="slug" name="slug" maxlength="255" value="{{ old('slug', $blog->slug) }}" placeholder="your-blog-title"><p class="help">/blog/<span id="slug-preview">{{ old('slug', $blog->slug) }}</span></p></div><div><label for="category" class="field">Category *</label><input id="category" name="category" required maxlength="100" list="blog-categories" value="{{ old('category', $blog->category) }}"><datalist id="blog-categories"><option>Delivery guides</option><option>Practical tips</option><option>Business insights</option><option>Behind the scenes</option></datalist></div></div><div><label for="excerpt" class="field">Short description *</label><textarea id="excerpt" name="excerpt" required rows="3" maxlength="1000">{{ old('excerpt', $blog->excerpt) }}</textarea><p class="help">A short introduction for the listing and featured article card.</p></div></section>
<section class="panel"><h2 class="mb-5 text-lg font-extrabold">Blog content</h2><textarea id="content" name="content" rows="24">{{ old('content', $blog->content ?: '<h1>Your article heading</h1><p>Start writing your story here…</p>') }}</textarea><p id="editor-status" class="help" role="status">Loading editor…</p></section>
<section class="panel space-y-5"><div><h2 class="text-lg font-extrabold">Search engine settings</h2><p class="help">Leave optional fields empty to use the blog title and short description.</p></div><div><label for="meta_title" class="field">Meta title</label><input id="meta_title" name="meta_title" maxlength="255" value="{{ old('meta_title', $blog->meta_title) }}" data-counter="60"><p class="help"><span id="meta_title-count">0</span> characters · Aim for around 50–60.</p></div><div><label for="meta_description" class="field">Meta description</label><textarea id="meta_description" name="meta_description" rows="3" maxlength="500" data-counter="160">{{ old('meta_description', $blog->meta_description) }}</textarea><p class="help"><span id="meta_description-count">0</span> characters · Aim for around 150–160.</p></div><div><label for="meta_keywords" class="field">Meta keywords</label><input id="meta_keywords" name="meta_keywords" maxlength="1000" value="{{ old('meta_keywords', $blog->meta_keywords) }}" placeholder="same day courier, delivery tips, UK courier"><p class="help">Separate keywords with commas.</p></div><div class="rounded-xl bg-slate-50 p-5"><p class="mb-3 text-[10px] font-bold uppercase tracking-wider text-slate-400">Search preview</p><p id="seo-preview-title" class="text-lg text-blue-700"></p><p class="my-1 break-all text-xs text-emerald-700">{{ rtrim(config('app.frontend_url'), '/') }}/blog/<span id="seo-preview-slug"></span></p><p id="seo-preview-description" class="text-sm leading-6 text-slate-600"></p></div><label class="flex items-center gap-2 text-xs"><input type="checkbox" name="noindex" value="1" @checked(old('noindex', $blog->noindex))> Ask search engines not to index this article (noindex)</label><label class="flex items-center gap-2 text-xs"><input type="checkbox" name="nofollow" value="1" @checked(old('nofollow', $blog->nofollow))> Ask search engines not to follow article links (nofollow)</label></section>
<section class="panel space-y-5"><h2 class="text-lg font-extrabold">Social sharing</h2><p class="help">Open Graph and Twitter cards use these fields. Empty fields fall back to your SEO details and featured image.</p><div><label for="og_title" class="field">Social title</label><input id="og_title" name="og_title" maxlength="255" value="{{ old('og_title', $blog->og_title) }}"></div><div><label for="og_description" class="field">Social description</label><textarea id="og_description" name="og_description" rows="3" maxlength="500">{{ old('og_description', $blog->og_description) }}</textarea></div><div><label for="og_image" class="field">Social image (optional)</label><input id="og_image" type="file" name="og_image" accept="image/jpeg,image/png,image/webp" class="text-xs">@if($blog->og_image_path)<img src="{{ Storage::disk('public')->url($blog->og_image_path) }}" class="mt-3 h-24 rounded-xl" alt="Current social sharing image">@endif<p class="help">JPG, PNG or WebP, up to 5 MB. Recommended: 1200 × 630 px.</p></div></section>
</div>
<div class="space-y-6 xl:sticky xl:top-6"><section class="panel space-y-5"><h2 class="text-lg font-extrabold">Publishing</h2><div><label for="status" class="field">Visibility</label><select id="status" name="status"><option value="draft" @selected(old('status', $blog->status) === 'draft')>Draft — only in admin</option><option value="published" @selected(old('status', $blog->status) === 'published')>Published — visible on website</option></select></div><label class="flex items-start gap-2 text-xs leading-5"><input type="checkbox" name="is_featured" value="1" class="mt-1" @checked(old('is_featured', $blog->is_featured))> Feature this blog on the listing page</label><button id="save-blog" class="w-full rounded-full bg-[#c6ff00] px-6 py-3.5 text-sm font-extrabold text-[#0a192f]">Save blog</button></section><section class="panel space-y-4"><h2 class="text-lg font-extrabold">Featured image *</h2><img id="image-preview" src="{{ $blog->image_path ? Storage::disk('public')->url($blog->image_path) : '' }}" alt="Featured image preview" class="w-full rounded-xl object-cover {{ $blog->image_path ? '' : 'hidden' }}" style="aspect-ratio:16/9"><label for="image" class="field">Upload image</label><input id="image" name="image" type="file" accept="image/jpeg,image/png,image/webp" @required(!$blog->image_path) class="w-full text-xs"><div><label for="image_alt" class="field">Image alt text *</label><input id="image_alt" name="image_alt" required maxlength="255" value="{{ old('image_alt', $blog->image_alt) }}"><p class="help">Describe the image for accessibility and search engines.</p></div></section></div>
</form>
<script id="blog-editor-config" type="application/json">{!! json_encode(['uploadUrl' => route('admin.blogs.upload'), 'csrf' => csrf_token()], JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) !!}</script>
<script src="/vendor/jodit/jodit.min.js"></script>
<script src="/js/blog-editor.js?v=3"></script>
@endsection
