@extends('admin.layout')
@section('content')
<div class="max-w-2xl mx-auto space-y-7"><div><p class="text-xs font-bold uppercase tracking-widest text-blue-600">Account protection</p><h1 class="mt-2 text-3xl font-extrabold text-slate-900">Login & Security</h1><p class="mt-2 text-sm text-slate-500">Update the administrator name, login email or password. Your current password is required for every change.</p></div>
@if($errors->any())<div class="rounded-2xl border border-red-200 bg-red-50 p-4 text-xs font-bold text-red-700"><ul class="list-disc pl-5 space-y-1">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ route('admin.security.update') }}" class="space-y-5 rounded-3xl border border-slate-200 bg-white p-8 shadow-sm">@csrf @method('PUT')
<div><label class="mb-1.5 block text-xs font-bold text-slate-700">Administrator name</label><input name="name" required value="{{ old('name',$user->name) }}" autocomplete="name" class="w-full rounded-xl border border-slate-300 px-4 py-3"></div>
<div><label class="mb-1.5 block text-xs font-bold text-slate-700">Login email</label><input name="email" type="email" required value="{{ old('email',$user->email) }}" autocomplete="username" class="w-full rounded-xl border border-slate-300 px-4 py-3"></div>
<div class="border-t border-slate-100 pt-5"><label class="mb-1.5 block text-xs font-bold text-slate-700">Current password</label><input name="current_password" type="password" required autocomplete="current-password" class="w-full rounded-xl border border-slate-300 px-4 py-3"></div>
<div class="grid gap-4 sm:grid-cols-2"><div><label class="mb-1.5 block text-xs font-bold text-slate-700">New password (optional)</label><input name="password" type="password" autocomplete="new-password" class="w-full rounded-xl border border-slate-300 px-4 py-3"><p class="mt-1 text-[10px] text-slate-500">Minimum 12 characters with uppercase, lowercase, number and symbol.</p></div><div><label class="mb-1.5 block text-xs font-bold text-slate-700">Confirm new password</label><input name="password_confirmation" type="password" autocomplete="new-password" class="w-full rounded-xl border border-slate-300 px-4 py-3"></div></div>
<button class="w-full rounded-xl bg-[#0a192f] py-3.5 text-sm font-extrabold text-white hover:bg-blue-700">Save security changes</button></form></div>
@endsection
